---
title: "FastAI Lesson 0: How to FastAI"
description: FastAI Lesson 0 Notes
author: "Pranav Rajan"
date: "2023-11-19"
categories: [learning, fastai, deep learning]
toc: true
---

I've recently started [FastAI Practical Deep Learning for Coders](https://course.fast.ai/) to learn about machine learning. To hold myself accountable and finish the course I am going to try to write a blog post for every video in the series starting with `Lesson 0`. By doing this my goal is to not only learn about deep learning and track my progress but reinforce my learning by trying to explain what I've learned for people new to machine learning like me. `Lesson 0` isn't officially presented in the course until `Lesson 3` but it provides valuable advice for how to complete FastAI and actually learn how to write deep learning code.

`Lesson 0` doesn't have any code examples or notebooks but I took Jeremy's advice about blogging and interacting with the community by setting up this Quarto blog as the `Lesson 0` project. `Lesson 0` was created in 2020 before Twitter became X and closed off to people who didn't have an account. Since then, some of the ML community and other academic communities in CS have migrated to `Discord` , `Mastodon`, and `Bluesky`. I'd recommend checking out the `FastAI Forums`, `FastAI Discord`, and `BlueSky`.

## Jeremy Howard's Advice

1.  Commit to finish the course
2.  Try to finish one really good project to show off what you've learned in the course
3.  Share and blog about your work

## How to Watch A FastAI Lesson

This advice was presented by Jeremy Howard in `Lesson 0`

1.  Watch FastAI Lecture

2.  Run notebooks and code presented in the lecture and experiment with code

3.  Reproduce notebook from a clean notebook (Jeremy provides clean notebooks on github)

4.  Repeat with a different dataset (could be personal project)

## Resources

1.  [FastAI Lesson 0: How to FastAI](https://www.youtube.com/watch?v=gGxe2mN3kAg)

2.  [Christine Mcleavey's Blog](https://christinemcleavey.com/learning-about-deep-learning/)

3.  [Quarto](https://quarto.org/)

4.  [Bluesky ](https://bsky.app/)