project:
  type: website
  output-dir: docs

website:
  title: "Pranav Rajan's Blog"
  site-url: https://mozartfish.github.io/blog
  description: "This is a blog"
  navbar:
    collapse: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mozartfish
      - icon: rss 
        href: index.xml

format:
  html:
    theme: cosmo
    css: styles.css



