---
title: "FastAI Lesson 1: Getting Started"
description: FastAI Lesson 1 Notes
author: "Pranav Rajan"
date: "2023-11-20"
categories: [learning, fastai, deep learning]
toc: true
---

## Summary

In this lesson, Jeremy walks through a bird classification example which in 2015 was considered the bleeding edge of state of the art. 8 years later, it's hard to believe that I can run this on my own local machine. Even though my training is in computer science, I conceptually found some of the definitions that Jeremy mentioned in the lesson such as model confusing which is where the Chapter 1 of the FastAI Book filled in the gaps. I would strongly recommend checking out the definitions in this chapter because they're still used today when talking about how a model like GPT-4.

## Terminology

-   **Machine Learning** - The training of programs developed by teaching a computer learn from experience rather than coding the individual steps

-   **Deep Learning** - A computer technique that uses layers of neural networks to extract and transform data. Neural networks layers are trained by algorithms that minimize their errors and improve their accuracy. This is how a network learns to perform a specific task. Deep learning is a sub-discipline of `machine learning`.

-   **Dataset** - A bunch of data ie. images, sounds, text, files or anything else.

-   **Label** - The data we're trying to predict ie. dog or cat.

-   **Independent Variable** - Data that does not include labels

-   **Dependent Variable** - the correct label ie. dog or cat. Also called **targets.**

-   **Architecture** - The structure of the model we're trying to fit. A mathematical function that we're passing the input data and parameters to.

-   **Parameters** - The values in the model that change what task it can do and are updated through model training. In Arthur Samuel's definitions the synonym for parameters is weights which has a different meaning in modern deep learning.

-   **Parameter(Weight) Assignment** - Particular choice of values for parameters.

-   **Weights** - A particular type of model parameter.

-   **Fit** - Update the model parameters such that the predictions of the model using the input data match the target labels.

-   **Train** - Synoym for fit.

-   **Pretrained Model** - A model that has already been trained, generally using a large dataset and will be fine-tuned ie. resnet class of models.

-   **Fine-Tune** - Update a pretrained model for a different task.

-   **Epoch** - One complete pass through the input data.

-   **Loss** - A measure of how good the model is, chosen to drive training via `Stochastic Gradient Descent (SGD)`.

-   **Metric** - A measurement of how good the model is, using the validation set, chosen for human consumption.

-   **Validation Set** - A set of data held out from training, used only for measuring how good the model is.

-   **Training Set** - The data used for fitting the model; does not include any data from the validation set.

-   **Overfitting** - Training a model in such a way that it remembers specific features of the input data rather than generalizing.

-   **Convolutional Neural Network (CNN)** - A type of neural network that works particularly well for computer vision tasks.

-   **Transfer Learning:** Using a pretrained model for a task different to what it was originally trained for.

-   

## Limitations of Machine Learning

1.  A model cannot be created without data
2.  A model can only learn to operate on patterns seen in input data used to train it
3.  This learning approach only creates `predictions` **not** `recommend actions`
4.  We need `labels` + `data` (pictures of dogs and cats that have labels saying which ones are dogs and which ones are cats)

## Resources

1.  [FastAI Lesson 1: Getting Started](https://course.fast.ai/Lessons/lesson1.html)

2.  [FastAI Chapter 1, Intro](https://colab.research.google.com/github/fastai/fastbook/blob/master/01_intro.ipynb)

3.  [Kaggle](https://www.kaggle.com/)

4.  [Google Colab](https://colab.google/)